version: '3'
services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./config-files/mysql/conf.d/:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: MyEpicPassword
            MYSQL_DATABASE: prestashop
        restart: always
    php:
        build:
            context: build-php
            args:
                phpbuild: 7.1-fpm
        expose:
            - "9000"
        depends_on:
            - mysql
        volumes:
            - ./www/:/var/www/html/
            - ./config-files/php/php.ini:/usr/local/etc/php/php.ini
        restart: always
    nginx:
        image: nginx
        ports:
            - "8002:80"
            - "443"
        depends_on:
            - php
        volumes:
            - ./www/:/var/www/html/
            - ./logs/nginx/:/var/log/nginx
            - ./config-files/nginx/conf.d/:/etc/nginx/conf.d
        restart: always

volumes:
    dbdata:
