version: '2'

services:
    apache:
        container_name: prestashop
        build: build/
        environment:
            PS_DOMAIN: localhost:8081
            PS_INSTALL_AUTO: 0
        ports:
            - "8081:80"
        volumes:
            - ./bdd:/tmp/bdd
